# Generated by Django 4.2.11 on 2026-05-04 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], max_length=10)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
